Adiciona regras de css para melhorar o estilo da aplicação
MemedDev/kanboard-style pull request #1
Opened 2018-06-08 04:57 UTC by csilva2810

Estava meio sem o que fazer em casa, aí resolvi dar uma fuçada no CSS do kanboard. 😃 

### Alterações
- Header
- Sidebar
- Espaçamentos
- Botões
- Dropdowns
- Fontes
- Campos de formulários
- Tasks Cards
- Cores

### Screenshots
![screenshot-kanboard memed com br-2018 06 08-01-09-49](https://user-images.githubusercontent.com/5983943/41139615-12c81362-6abf-11e8-8abd-1ca203e0807a.png)
![screenshot-kanboard memed com br-2018 06 08-01-52-26 1](https://user-images.githubusercontent.com/5983943/41139634-3f20b23e-6abf-11e8-956f-1e651384adbf.png)

2018-06-08 12:51 UTC, williamespindola commented
A cor padrão da milestone é amarela e a cor da fonte esta amarela.
![screen shot 2018-06-08 at 09 49 58](https://user-images.githubusercontent.com/794521/41159031-7ebb806c-6b01-11e8-8281-7e27d192496b.png)

2018-06-08 13:14 UTC, csilva2810 commented
Coloquei a cor na propriedade **color**, era pra ter colocado em **background-color**

```
.task-summary-container.color-yellow {
    color: #ffd600;
}
```

2018-06-08 13:15 UTC, williamespindola requested changes

2018-06-08 13:15 UTC, williamespindola commented on style.css
> +    padding: 6px !important;
O tamanho das tags ficou muito grande, fica ruim quando tem mitas tags na task. Acho que `1px 5px !important` fica melhor, menos poluído.
![screen shot 2018-06-08 at 09 59 24](https://user-images.githubusercontent.com/794521/41159360-a677d546-6b02-11e8-9447-15e6dbf76cf9.png)

2018-06-08 13:15 UTC, williamespindola commented on style.css
> +    padding-right: 15px;
Use `padding 0px 15px;` para ficar com a mesma quantidade espaço dos dois dados do conteúdo.

2018-06-08 13:15 UTC, williamespindola commented on style.css
> +    padding: 15px;
use `padding: 0px 15px` pois o título da sidebar não esta alinhado com altura do título da task

2018-06-08 17:27 UTC, csilva2810 commented
@williamespindola Ajustei os pontos que você pediu!

2018-06-11 14:41 UTC, williamespindola commented
Merge via [f2975bc](https://github.com/MemedDev/kanboard-style/commit/f2975bcc8974498379acfe4776cbc05508c80626)

2018-06-11 14:41 UTC, closed without merging